# Generated by Django 5.2.4 on 2025-08-02 04:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posteo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='fecha',
        ),
        migrations.AddField(
            model_name='posteo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posteo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categoria'),
        ),
    ]
