# Generated by Django 5.2.4 on 2025-08-06 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_posteo_fecha_posteo_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
